server:
  port: 3000

spring:
  #프로필 설정
  profiles:
    active: dev

  #데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PROJECT
    password: _aA123456



  #파일 업로드 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 40MB

  # 정적 자원 설정(CSS,JS,image 등)
  resources:
    staticLocations: file:src/main/resources/static/

  #live reload 설정(배포시 제거)
  devtools:
    livereload:
      enabled: true

  # thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  flyway:
    enabled: true

file:
  upload:
    path: C:/uploads/
    url: /uploads/

#로거 설정
logging:
  level:
    org:
      springframework:
        jdbc: trace
